"use client";
import { useState, useTransition } from "react";
import { checkPageSpeed, loadSearchConsole } from "./actions";
export function SeoTools() {
 const [pending, start] = useTransition();
 const [speed, setSpeed] = useState<Awaited<ReturnType<typeof checkPageSpeed>> | null>(null);
 const [search, setSearch] = useState<Awaited<ReturnType<typeof loadSearchConsole>> | null>(null);
 return <div className="mt-6 space-y-8"><section><h2 className="text-lg font-medium">Mobile PageSpeed</h2><p className="mt-2 text-sm text-muted">Run on demand. Results are cached for 24 hours; this never runs for public visitors.</p><button disabled={pending} onClick={() => start(async () => setSpeed(await checkPageSpeed()))} className="mt-3 rounded-md bg-primary px-4 py-3 text-sm text-white">{pending ? "Loading…" : "Check PageSpeed"}</button>{speed?.error ? <p role="alert" className="mt-3 text-sm">{speed.error}</p> : null}{speed && "scores" in speed ? <div className="mt-4 space-y-2 text-sm"><p>Checked: {speed.checkedAt}</p>{speed.scores?.map(s => <p key={s.title}>{s.title}: {s.score ?? "Unavailable"}</p>)}{speed.metrics?.map(m => <p key={m.title}>{m.title}: {m.value || "Unavailable"}</p>)}</div> : null}</section><section><h2 className="text-lg font-medium">Search Console queries</h2><p className="mt-2 text-sm text-muted">Last 28 available days. Google returns top queries; these rows are not site-wide totals.</p><button disabled={pending} onClick={() => start(async () => setSearch(await loadSearchConsole()))} className="mt-3 rounded-md bg-primary px-4 py-3 text-sm text-white">Load search data</button>{search?.error ? <p role="alert" className="mt-3 text-sm">{search.error}</p> : null}{search && "rows" in search ? <><p className="mt-4 text-xs text-muted">{search.startDate} to {search.endDate}</p>{!search.rows?.length ? <p className="mt-3 text-sm">No query data in this period.</p> : <div className="mt-3 divide-y divide-border-soft">{search.rows.map(row => <div key={row.keys.join("/")} className="py-3 text-sm"><p className="font-medium">{row.keys.join(" / ")}</p><p className="mt-1 text-xs text-muted">{row.clicks} clicks · {row.impressions} impressions · {(row.ctr * 100).toFixed(1)}% CTR · position {row.position.toFixed(1)}</p></div>)}</div>}</> : null}</section></div>;
}
