"use client";
import { useState, useTransition } from "react";
import Link from "next/link";
import { localityPath, type LocalityPage } from "@/lib/localities";
import { saveLocality, deleteLocality } from "./actions";
const empty = { name: "", city: "", city_slug: "", slug: "", intro: "", content: "", local_details: "", seo_title: "", seo_description: "", service_ids: [] as string[], project_ids: [] as string[], faqs: [] as LocalityPage["faqs"], published: false };
export function LocalityEditor({ pages, services, projects }: { pages: LocalityPage[]; services: { id: string; title: string }[]; projects: { id: string; title: string }[] }) {
  const [draft, setDraft] = useState<Partial<LocalityPage>>(empty);
  const [message, setMessage] = useState(""); const [pending, start] = useTransition();
  function field(key: keyof typeof empty, label: string, multiline = false) {
    const props = { className: "mt-1 w-full rounded-md border border-border-soft bg-surface p-3 text-sm", value: String(draft[key] ?? ""), onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setDraft({ ...draft, [key]: event.target.value }) };
    return <label className="block text-sm" key={key}>{label}{multiline ? <textarea {...props} rows={key === "content" ? 8 : 3} /> : <input {...props} />}</label>;
  }
  return <><div className="my-5 flex flex-wrap gap-2"><button type="button" onClick={() => { setDraft(empty); setMessage(""); }} className="rounded-md bg-primary px-3 py-2 text-sm text-white">New page</button>{pages.map(page => <button key={page.id} type="button" onClick={() => { setDraft(page); setMessage(""); }} className="rounded-md border border-border-soft px-3 py-2 text-sm">{page.name} · {page.published ? "Live" : "Draft"}</button>)}</div><form className="space-y-4" onSubmit={event => { event.preventDefault(); start(async () => { const result = await saveLocality(draft); setMessage(result.error || "Saved successfully."); if (result.id) setDraft({ ...draft, id: result.id }); }); }}>
    {field("name", "Page name (e.g. Thane or Hiranandani Estate)")}{field("city", "City")}{field("city_slug", "City URL slug (e.g. thane)")}{field("slug", "Locality URL slug — leave empty for the city page")}
    <p className="text-xs text-muted">URL: {localityPath({ city_slug: draft.city_slug || "city", slug: draft.slug || "" })}</p>
    {field("intro", "Introduction", true)}{field("content", "Service information — plain text, separate paragraphs with a blank line", true)}{field("local_details", "Actual local details: coverage, site access, nearby work or quotation considerations", true)}
    {([['service_ids', 'Services available here', services], ['project_ids', 'Relevant completed projects (their actual locations remain visible)', projects]] as const).map(([key, label, items]) => <fieldset key={key} className="space-y-2"><legend className="mb-2 text-sm font-medium">{label}</legend>{items.map(item => <label key={item.id} className="flex gap-2 text-sm"><input type="checkbox" checked={draft[key]?.includes(item.id) || false} onChange={e => setDraft({ ...draft, [key]: e.target.checked ? [...(draft[key] || []), item.id] : (draft[key] || []).filter(id => id !== item.id) })} />{item.title}</label>)}</fieldset>)}
    <fieldset><legend className="text-sm font-medium">Local questions and answers</legend>{draft.faqs?.map((faq, index) => <div key={index} className="mt-3 space-y-2"><input aria-label={`Question ${index + 1}`} placeholder="Question" className="w-full rounded-md border border-border-soft p-3 text-sm" value={faq.question} onChange={e => setDraft({ ...draft, faqs: draft.faqs!.map((f, i) => i === index ? { ...f, question: e.target.value } : f) })} /><textarea aria-label={`Answer ${index + 1}`} placeholder="Answer" className="w-full rounded-md border border-border-soft p-3 text-sm" value={faq.answer} onChange={e => setDraft({ ...draft, faqs: draft.faqs!.map((f, i) => i === index ? { ...f, answer: e.target.value } : f) })} /><button type="button" className="text-xs text-red-700" onClick={() => setDraft({ ...draft, faqs: draft.faqs!.filter((_, i) => i !== index) })}>Remove question</button></div>)}<button type="button" className="mt-3 text-sm underline" onClick={() => setDraft({ ...draft, faqs: [...(draft.faqs || []), { question: "", answer: "" }] })}>Add question</button></fieldset>
    {field("seo_title", "SEO title (optional)")}{field("seo_description", "SEO description (optional)")}
    <label className="flex gap-2 text-sm"><input type="checkbox" checked={draft.published || false} onChange={e => setDraft({ ...draft, published: e.target.checked })} />Publish page</label>
    <p role="status" className="text-sm">{message}</p><div className="flex items-center gap-4"><button disabled={pending} className="rounded-md bg-primary px-5 py-3 text-sm text-white">{pending ? "Saving…" : "Save page"}</button>{draft.published && draft.id ? <Link className="text-sm underline" href={localityPath({ city_slug: draft.city_slug!, slug: draft.slug || "" })}>View page</Link> : null}{draft.id ? <button type="button" disabled={pending} className="text-sm text-red-700" onClick={() => { if (window.confirm("Delete this locality page?")) start(async () => { const result = await deleteLocality(draft.id!); setMessage(result.error || "Deleted."); if (!result.error) setDraft(empty); }); }}>Delete</button> : null}</div>
  </form></>;
}
